// Elm REPL running entirely in the browser.
//
// The Elm compiler (ported to Elm, see repl-worker/) runs in a Web Worker. All files it needs
// are downloaded once when the page loads and kept in memory, so restarting the REPL
// (e.g. after interrupting an endless loop with Ctrl+C) needs no further requests.

'use strict';

// ASSETS

const replAssets = (function () {
    // repl/assets.js is generated by the build and loaded with a script tag (not fetch),
    // so this also works when index.html is opened from the file system
    function loadScript(src) {
        return new Promise(function (resolve, reject) {
            const script = document.createElement('script');
            script.src = src;
            script.onload = resolve;
            script.onerror = function () {
                reject(new Error('Could not load ' + src));
            };
            document.head.appendChild(script);
        });
    }

    function scriptUrl(code) {
        return URL.createObjectURL(new Blob([code], { type: 'text/javascript' }));
    }

    return loadScript('repl/assets.js').then(function () {
        const data = window.replAssetData;
        delete window.replAssetData;
        return {
            worker: scriptUrl(data.worker),
            formatWorker: scriptUrl(data.formatWorker),
            elmHome: data.elmHome,      // base64
            project: data.project,      // base64
        };
    });
})();


// REPL WORKER

// One worker = one `elm repl` process. Every request (init or input line) gets exactly one response.
class ReplWorker {
    constructor(assets, onError) {
        this.waiting = [];
        this.worker = new Worker(assets.worker);
        this.worker.onmessage = (event) => {
            const resolve = this.waiting.shift();
            if (resolve) resolve(event.data);
        };
        this.worker.onerror = (event) => {
            event.preventDefault();
            onError(event.message || 'unknown error');
        };
        this.ready = this.request({ type: 'init', elmHome: assets.elmHome, project: assets.project });
    }

    request(msg) {
        return new Promise((resolve) => {
            this.waiting.push(resolve);
            this.worker.postMessage(msg);
        });
    }

    send(line) {
        return this.request({ type: 'input', line: line });
    }

    writeFile(path, content) {
        this.worker.postMessage({ type: 'write', path: path, content: content });
    }

    cancelInput() {
        this.worker.postMessage({ type: 'cancel' });
    }

    // pending requests are resolved with null
    terminate() {
        this.worker.terminate();
        const waiting = this.waiting;
        this.waiting = [];
        waiting.forEach((resolve) => resolve(null));
    }
}


// TERMINAL

const PROMPT = '> ';
const CONTINUATION_PROMPT = '| ';

class ReplTerminal {
    // term: xterm.js Terminal (with convertEol: true)
    // getCode: returns the current content of the editor (src/Main.elm)
    // onStopped: called when the REPL was stopped with :exit or failed
    constructor(term, getCode, onStopped) {
        this.term = term;
        this.getCode = getCode;
        this.onStopped = onStopped;

        this.repl = null;
        this.assets = null;
        this.writtenCode = null;

        this.queue = [];          // pending keyboard input
        this.state = 'loading';   // loading | prompt | busy | stopped
        this.processing = false;
        this.replaying = false;

        // line editor
        this.prompt = PROMPT;
        this.buffer = '';
        this.cursor = 0;
        this.history = [];
        this.historyIndex = 0;
        this.historyDraft = '';

        // lines of the current (possibly multi-line) input and of all completed inputs,
        // used to restore the REPL state after an interrupt
        this.group = [];
        this.completed = [];

        // output queue (see output()), the line where the prompt starts and the pending redraw
        this.pending = [];
        this.promptMarker = null;
        this.renderOutput = () => this.renderSequence();

        term.onData((data) => this.input(data));
        term.onResize(() => {
            if (this.state === 'prompt') {
                this.render();
            }
        });
    }

    // All output goes through this queue. Functions in it are called when xterm has processed
    // everything before them, so they can use the real cursor position. This keeps the input
    // line correct when the terminal is resized (xterm does not always rewrap wrapped lines).
    output(data) {
        this.pending.push(data);
        if (this.pending.length === 1) {
            this.flushOutput();
        }
    }

    flushOutput() {
        while (this.pending.length > 0) {
            const data = this.pending[0];
            if (typeof data === 'function') {
                this.term.write('', () => {
                    this.pending.shift();
                    this.term.write(data());
                    this.flushOutput();
                });
                return;
            }
            this.term.write(data);
            this.pending.shift();
        }
    }

    // remembers the current line as the first line of the prompt (xterm moves markers along
    // when lines scroll or are rewrapped)
    markPromptLine() {
        this.output(() => {
            if (this.promptMarker) this.promptMarker.dispose();
            this.promptMarker = this.term.registerMarker(0);
            return '';
        });
    }

    // moves the cursor to the first line of the prompt and clears everything below
    clearPromptSequence() {
        const buffer = this.term.buffer.active;
        const marker = this.promptMarker;
        const up = marker && !marker.isDisposed ? buffer.baseY + buffer.cursorY - marker.line : 0;
        return (up > 0 ? '\x1b[' + up + 'A' : '') + '\r\x1b[J';
    }

    // Starts the REPL and types `initialInput` as if the user did it.
    start(initialInput) {
        this.output('Loading the Elm compiler ...');
        return replAssets.then((assets) => {
            this.assets = assets;
            return this.startWorker();
        }).then((banner) => {
            if (!banner) return;
            // the loading message is the only output so far: clear the screen and the scrollback
            this.output('\x1b[H\x1b[2J\x1b[3J');
            this.writeMessages(banner.messages);
            this.showPrompt(PROMPT, '');
            if (initialInput) {
                this.type(initialInput);
            }
        }).catch((error) => this.fail(error));
    }

    // Starts a fresh REPL (after :exit), like opening a new terminal.
    restart(initialInput) {
        if (this.repl) this.repl.terminate();
        this.queue = [];
        this.group = [];
        this.completed = [];
        this.writtenCode = null;
        this.output('\r\n');
        this.startWorker().then((banner) => {
            if (!banner) return;
            this.writeMessages(banner.messages);
            this.showPrompt(PROMPT, '');
            if (initialInput) {
                this.type(initialInput);
            }
        }).catch((error) => this.fail(error));
    }

    startWorker() {
        this.repl = new ReplWorker(this.assets, (message) => this.fail(message));
        return this.repl.ready;
    }

    fail(error) {
        this.state = 'stopped';
        this.output('\r\n\x1b[31mThe Elm REPL failed: ' + error + '\x1b[0m\r\n');
        this.onStopped();
    }

    // Text typed or pasted into the terminal
    type(text) {
        this.input(text.replace(/\r?\n/g, '\r'));
    }

    // Writes the editor content to src/Main.elm if it changed (like saving the file)
    syncCode() {
        if (!this.repl) return;
        const code = this.getCode();
        if (code !== this.writtenCode) {
            this.repl.writeFile('/src/Main.elm', code);
            this.writtenCode = code;
        }
    }

    input(data) {
        if (data === '\x03' && this.state === 'busy') {
            this.interrupt();
            return;
        }
        if (this.state === 'stopped') {
            return;
        }
        // split into single keys, keeping escape sequences together
        const keys = data.match(/\x1b(\[[0-9;]*[ -\/]*[@-~]|O.|.)?|[\s\S]/g) || [];
        this.queue.push.apply(this.queue, keys);
        this.process();
    }

    async process() {
        if (this.processing) return;
        this.processing = true;
        try {
            while (this.state === 'prompt' && this.queue.length > 0) {
                const key = this.queue.shift();
                if (key === '\r' || key === '\n') {
                    await this.submit();
                } else {
                    this.handleKey(key);
                }
            }
        } finally {
            this.processing = false;
        }
    }

    handleKey(key) {
        switch (key) {
            case '\x7f': // Backspace
            case '\b':
                if (this.cursor > 0) {
                    this.edit(this.buffer.slice(0, this.cursor - 1) + this.buffer.slice(this.cursor), this.cursor - 1);
                }
                break;
            case '\x1b[3~': // Delete
            case '\x04': // Ctrl+D
                if (this.cursor < this.buffer.length) {
                    this.edit(this.buffer.slice(0, this.cursor) + this.buffer.slice(this.cursor + 1), this.cursor);
                }
                break;
            case '\x1b[D': // Left
            case '\x02': // Ctrl+B
                this.edit(this.buffer, Math.max(0, this.cursor - 1));
                break;
            case '\x1b[C': // Right
            case '\x06': // Ctrl+F
                this.edit(this.buffer, Math.min(this.buffer.length, this.cursor + 1));
                break;
            case '\x1b[1;5D': // Ctrl+Left
            case '\x1bb': // Alt+B
                this.edit(this.buffer, this.wordStart());
                break;
            case '\x1b[1;5C': // Ctrl+Right
            case '\x1bf': // Alt+F
                this.edit(this.buffer, this.wordEnd());
                break;
            case '\x1b[H': // Home
            case '\x1bOH':
            case '\x1b[1~':
            case '\x01': // Ctrl+A
                this.edit(this.buffer, 0);
                break;
            case '\x1b[F': // End
            case '\x1bOF':
            case '\x1b[4~':
            case '\x05': // Ctrl+E
                this.edit(this.buffer, this.buffer.length);
                break;
            case '\x1b[A': // Up
            case '\x10': // Ctrl+P
                this.browseHistory(-1);
                break;
            case '\x1b[B': // Down
            case '\x0e': // Ctrl+N
                this.browseHistory(1);
                break;
            case '\x15': // Ctrl+U
                this.edit(this.buffer.slice(this.cursor), 0);
                break;
            case '\x0b': // Ctrl+K
                this.edit(this.buffer.slice(0, this.cursor), this.cursor);
                break;
            case '\x17': { // Ctrl+W
                const start = this.wordStart();
                this.edit(this.buffer.slice(0, start) + this.buffer.slice(this.cursor), start);
                break;
            }
            case '\x0c': // Ctrl+L
                this.output('\x1b[H\x1b[2J');
                this.markPromptLine();
                this.render();
                break;
            case '\x03': // Ctrl+C: discard the current input
                this.edit(this.buffer, this.buffer.length);
                this.output('^C\r\n');
                if (this.group.length > 0) {
                    this.repl.cancelInput();
                    this.group = [];
                }
                this.showPrompt(PROMPT, '');
                break;
            case '\t':
                this.insert('    ');
                break;
            default:
                if (key.length === 1 && key >= ' ') {
                    // insert consecutive printable characters at once (fast pasting)
                    let text = key;
                    while (this.queue.length > 0 && this.queue[0].length === 1 && this.queue[0] >= ' ' && this.queue[0] !== '\x7f') {
                        text += this.queue.shift();
                    }
                    this.insert(text);
                }
        }
    }

    insert(text) {
        this.edit(this.buffer.slice(0, this.cursor) + text + this.buffer.slice(this.cursor), this.cursor + text.length);
    }

    wordStart() {
        let i = this.cursor;
        while (i > 0 && !/\w/.test(this.buffer[i - 1])) i--;
        while (i > 0 && /\w/.test(this.buffer[i - 1])) i--;
        return i;
    }

    wordEnd() {
        let i = this.cursor;
        while (i < this.buffer.length && !/\w/.test(this.buffer[i])) i++;
        while (i < this.buffer.length && /\w/.test(this.buffer[i])) i++;
        return i;
    }

    browseHistory(direction) {
        const index = this.historyIndex + direction;
        if (index < 0 || index > this.history.length) return;
        if (this.historyIndex === this.history.length) {
            this.historyDraft = this.buffer;
        }
        this.historyIndex = index;
        const line = index === this.history.length ? this.historyDraft : this.history[index];
        this.edit(line, line.length);
    }

    edit(buffer, cursor) {
        this.buffer = buffer;
        this.cursor = cursor;
        this.render();
    }

    // Redraws prompt and input (when xterm has processed the previous output).
    render() {
        if (this.pending[this.pending.length - 1] !== this.renderOutput) {
            this.output(this.renderOutput);
        }
    }

    // Handles lines that are wider than the terminal.
    renderSequence() {
        const cols = this.term.cols;
        let out = this.clearPromptSequence() + this.prompt + this.buffer;
        const end = this.prompt.length + this.buffer.length;
        if (end > 0 && end % cols === 0) {
            // move the cursor out of the pending wrap state into the next row
            out += ' \b';
        }
        const endRow = Math.floor(end / cols);
        const pos = this.prompt.length + this.cursor;
        const row = Math.floor(pos / cols);
        const col = pos % cols;
        if (endRow > row) out += '\x1b[' + (endRow - row) + 'A';
        out += '\r';
        if (col > 0) out += '\x1b[' + col + 'C';
        return out;
    }

    showPrompt(prompt, prefill) {
        this.state = 'prompt';
        this.prompt = prompt;
        this.buffer = prefill || '';
        this.cursor = this.buffer.length;
        this.historyIndex = this.history.length;
        this.markPromptLine();
        this.render();
        this.process();
    }

    writeMessages(messages) {
        for (const message of messages) {
            this.output(message + '\n');
        }
    }

    async submit() {
        const line = this.buffer;
        this.edit(line, line.length);
        this.output('\r\n');
        if (line.trim() !== '' && this.history[this.history.length - 1] !== line) {
            this.history.push(line);
        }
        if (this.group.length === 0) {
            this.syncCode();
        }
        this.group.push(line);

        this.state = 'busy';
        const repl = this.repl;
        const response = await repl.send(line);
        if (response === null || repl !== this.repl) {
            // the worker was interrupted in the meantime
            return;
        }
        this.writeMessages(response.logs);
        this.writeMessages(response.messages);

        if (!response.running) {
            this.state = 'stopped';
            this.queue = [];
            this.onStopped();
        } else if (response.prefill !== null) {
            this.showPrompt(CONTINUATION_PROMPT, response.prefill);
        } else {
            this.completed.push.apply(this.completed, this.group);
            this.group = [];
            this.showPrompt(PROMPT, '');
        }
    }

    // Ctrl+C while evaluating: stop the worker, start a new one and replay all completed inputs
    // (if the replay itself is interrupted, start without the previous inputs)
    async interrupt() {
        const replay = this.replaying ? [] : this.completed;
        this.replaying = false;
        this.completed = [];
        this.repl.terminate();
        this.queue = [];
        this.group = [];
        this.writtenCode = null;
        this.state = 'busy';
        this.output('^C\r\n\x1b[33mInterrupted. Restarting the REPL ...\x1b[0m\r\n');

        const repl = new ReplWorker(this.assets, (message) => this.fail(message));
        this.repl = repl;
        if (await repl.ready === null || repl !== this.repl) return; // interrupted again
        this.syncCode();
        if (replay.length > 0) {
            this.replaying = true;
            for (const line of replay) {
                await repl.send(line);
                if (repl !== this.repl) return; // interrupted again
            }
            this.replaying = false;
            this.output('\x1b[33mPrevious inputs restored.\x1b[0m\r\n');
        }
        this.completed = replay;
        this.showPrompt(PROMPT, '');
    }
}

window.ReplTerminal = ReplTerminal;
window.replAssets = replAssets;
